apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubevirt-ui-viewer
  labels: {{- include "kvui.labels" . | nindent 4 }}
rules:
{{ include "kvui.rules.viewer" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubevirt-ui-operator
  labels: {{- include "kvui.labels" . | nindent 4 }}
rules:
{{ include "kvui.rules.viewer" . }}
{{ include "kvui.rules.operator" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubevirt-ui-owner
  labels: {{- include "kvui.labels" . | nindent 4 }}
rules:
{{ include "kvui.rules.viewer" . }}
{{ include "kvui.rules.operator" . }}
{{ include "kvui.rules.owner" . }}
